### ISSUE TITLE
Add cmd arg -d pid

### ISSUE THREAD

**Issue by stevenklar** [Broihon/GH-Injector-GUI#14]
Use case is the there are two processes with the same name. GH Injector finds one of those.
If I want to inject via CmdArgs I can only use -p for the process name, but not the process id directly.

This seems like a low hanging fruit. What do you think?

**Comment by Broihon** [comment]
Allready implemented in my local branch. I originally did not include that option as CmdArgs was intended mainly for shortcut usage. And since PIDs tend to change it wouldn't make much sense to include a PID option for shortcuts. For .bat and console usage it makes sense though.
Obviously -i will not support -wait.

**Comment by stevenklar** [comment]
Awesome. Well, nobody can predict pid's, so no wait ye.

Awaiting the integration into the main branch. :-)

**Comment by Broihon** [comment]
See newest commit. Added PID as -i.
